version: "3.8"

services:
  app:
    build: .
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
